apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      values: |
        server:
          affinity: ""
          ha:
            enabled: true
            raft:
              enabled: true
        injector:
          enabled: true
        csi:
          enabled: true
        ui:
          enabled: true
          serviceType: "LoadBalancer"
          serviceNodePort: null
          externalPort: 8200
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true       
      selfHeal: true    
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-secrets-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault-secrets-operator
    targetRevision: 0.9.1
    helm:
      values: |
        defaultVaultConnection:
          enabled: true
          address: "http://vault.vault.svc.cluster.local:8200"
          skipTLSVerify: false
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true       
      selfHeal: true    
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-resources
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/qjoly/homelab
    targetRevision: main
    path: home/system/vault
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true